// ─────────────────────────────────────────────────────────────
// BuyCoon! — Data Layer
// Structure mirrors Supabase schema for easy DB migration
// ─────────────────────────────────────────────────────────────
import { IMAGES } from './imagenes.js';

export const CATEGORIES = [
  { id: 'all',         label: 'All',         icon: '✦' },
  { id: 'electronics', label: 'Electronics', icon: '💻' },
  { id: 'fashion',     label: 'Fashion',     icon: '👗' },
  { id: 'home',        label: 'Home',        icon: '🏠' },
  { id: 'sports',      label: 'Sports',      icon: '⚽' },
  { id: 'vehicles',    label: 'Vehicles',    icon: '🚗' },
  { id: 'books',       label: 'Books',       icon: '📚' },
  { id: 'gaming',      label: 'Gaming',      icon: '🎮' },
  { id: 'music',       label: 'Music',       icon: '🎸' },
  { id: 'art',         label: 'Art',         icon: '🎨' },
  { id: 'babies',      label: 'Baby & Kids', icon: '🧸' },
  { id: 'tools',       label: 'Tools',       icon: '🔧' },
  { id: 'free',        label: 'Free 🎁',     icon: '🎁' },
];

export const CONDITIONS = [
  { id: 'new',       label: 'Brand New', color: '#34d399' },
  { id: 'excellent', label: 'Excellent', color: '#60a5fa' },
  { id: 'good',      label: 'Good',      color: '#716BC9' },
  { id: 'fair',      label: 'Fair',      color: '#fbbf24' },
  { id: 'for-parts', label: 'For Parts', color: '#E01A4F' },
];

export const MOCK_USERS = [
  { id:'u1', name:'Alejandra Moreno', handle:'@ale.moreno', avatar:'https://i.pravatar.cc/150?img=47', verified:true,  rating:4.9, sales:127, joined:'Jan 2023', location:'Panama City', bio:'Design enthusiast selling quality items. Fast replies!' },
  { id:'u2', name:'Ricardo Vargas',   handle:'@ricard.v',   avatar:'https://i.pravatar.cc/150?img=33', verified:false, rating:4.6, sales:43,  joined:'Mar 2023', location:'Colón',       bio:'Electronics and gadgets. All tested before selling.' },
  { id:'u3', name:'Valentina Cruz',   handle:'@vale_cr',    avatar:'https://i.pravatar.cc/150?img=29', verified:true,  rating:4.8, sales:89,  joined:'Nov 2022', location:'David, Chiriquí', bio:'Professional seller. Check my 5-star reviews!' },
  { id:'u4', name:'Mario Salas',      handle:'@mario.s',    avatar:'https://i.pravatar.cc/150?img=12', verified:false, rating:4.3, sales:21,  joined:'Jun 2023', location:'La Chorrera',  bio:'Moving sale — everything must go!' },
  { id:'u5', name:'Sofia Ríos',       handle:'@sofi.rios',  avatar:'https://i.pravatar.cc/150?img=23', verified:true,  rating:4.7, sales:55,  joined:'Feb 2023', location:'Arraiján',     bio:'Baby & kids specialist. Everything well-cared for.' },
  { id:'u6', name:'Carlos Tejada',    handle:'@carl.tej',   avatar:'https://i.pravatar.cc/150?img=8',  verified:false, rating:4.1, sales:12,  joined:'Aug 2023', location:'Chitré',       bio:'Clearing out my garage. Good deals guaranteed.' },
  { id:'u7', name:'Mariana Perez',    handle:'@mari.p',     avatar:'https://i.pravatar.cc/150?img=44', verified:true,  rating:4.9, sales:201, joined:'Sep 2022', location:'Panama City',  bio:'Top seller on BuyCoon! Thousands of happy buyers.' },
  { id:'u8', name:'Diego Fuentes',    handle:'@dieg.f',     avatar:'https://i.pravatar.cc/150?img=15', verified:false, rating:4.4, sales:34,  joined:'Apr 2023', location:'Penonomé',     bio:'College student selling stuff I no longer need.' },
];

// ─── HELPER ───────────────────────────────────────────────────
export const formatPrice = (price, currency = 'USD') => {
  if (price === 0) return 'FREE';
  return new Intl.NumberFormat('en-US', { style:'currency', currency, minimumFractionDigits:0 }).format(price);
};
export const isFree = (product) => product.price === 0;
export const getProductById = (id)    => MOCK_PRODUCTS.find(p => p.id === id);
export const getSellerById  = (id)    => MOCK_USERS.find(u => u.id === id);
export const getRelated     = (prod)  => MOCK_PRODUCTS.filter(p => p.id !== prod.id && p.category === prod.category).slice(0,4);
export const getFeatured    = ()      => MOCK_PRODUCTS.filter(p => p.favorites > 10).sort((a,b) => b.favorites - a.favorites).slice(0,8);
export const getTrending    = ()      => [...MOCK_PRODUCTS].sort((a,b) => b.views - a.views).slice(0,8);
export const getLowCost     = ()      => MOCK_PRODUCTS.filter(p => p.price <= 30 && p.price > 0).sort((a,b) => a.price - b.price);
export const getFreeItems   = ()      => MOCK_PRODUCTS.filter(p => p.price === 0);
export const getSellerProducts = (uid) => MOCK_PRODUCTS.filter(p => p.seller === uid);
export const distanceKm = (la1,lo1,la2,lo2) => {
  const R=6371, dLa=(la2-la1)*Math.PI/180, dLo=(lo2-lo1)*Math.PI/180;
  const a=Math.sin(dLa/2)**2+Math.cos(la1*Math.PI/180)*Math.cos(la2*Math.PI/180)*Math.sin(dLo/2)**2;
  return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));
};

export const ANNOUNCEMENT_SLIDES = [
  { id:'s1', type:'premium', productId:'p12', headline:'Premium listing', sub:'Rolex Submariner — Full set · Panama City', price:'$11,500', image: IMAGES.rolex[0],        cta:'View now', accent:'#716BC9' },
  { id:'s2', type:'deal',    productId:'p21', headline:'🔥 Hot deal',      sub:'Nike Air Zoom Pegasus — Like new · $60',    price:'$60',     image: IMAGES.nikePegasus[0],  cta:'Grab it',  accent:'#E01A4F' },
  { id:'s3', type:'free',    productId:'p35', headline:'🎁 Free item',     sub:'IKEA Lamp — Completely free · Arraiján',    price:'FREE',    image: IMAGES.ikeaFloorLamp[0],cta:'Claim it', accent:'#34d399' },
  { id:'s4', type:'deal',    productId:'p22', headline:'💜 Low-cost find', sub:'Nintendo Switch Lite — Excellent · $165',   price:'$165',    image: IMAGES.switchLite[0],   cta:'Check it', accent:'#8B416F' },
];

// ─── PRODUCTS ─────────────────────────────────────────────────
export const MOCK_PRODUCTS = [
  // ── PREMIUM ──────────────────────────────────────────────
  { id:'p1',  title:'MacBook Pro 14" M3 Pro',            price:350, currency:'USD', category:'electronics', condition:'excellent', location:'Marbella, Panama City',      lat:8.9936, lng:-79.5197, seller:'u1', tags:['apple','laptop'],       views:234, favorites:18, createdAt:'2025-04-20', available:true, images: IMAGES.macbook,       description:'MacBook Pro in excellent condition. Original charger, 8 months use. Battery 97%. Perfect for creative work or development.' },
  { id:'p2',  title:'Sony A7 IV Camera Body',            price:750, currency:'USD', category:'electronics', condition:'excellent', location:'El Cangrejo, Panama City',   lat:8.9824, lng:-79.5228, seller:'u3', tags:['sony','camera'],        views:189, favorites:31, createdAt:'2025-04-22', available:true, images: IMAGES.sonyA7,        description:'Sony A7 IV mirrorless body. Only 5,000 shutter count. Extra battery and strap included.' },
  { id:'p3',  title:'Herman Miller Aeron Chair',          price:80,  currency:'USD', category:'home',        condition:'good',      location:'Costa del Este, Panama City', lat:9.0076, lng:-79.4746, seller:'u2', tags:['chair','office'],       views:112, favorites:9,  createdAt:'2025-04-18', available:true, images: IMAGES.hermanMiller,  description:'Herman Miller Aeron size B ergonomic chair. Adjustable lumbar. Perfect WFH setup.' },
  { id:'p4',  title:'iPhone 15 Pro Max 256GB',            price:400, currency:'USD', category:'electronics', condition:'good',      location:'Punta Pacífica, Panama City', lat:8.9908, lng:-79.5079, seller:'u1', tags:['apple','iphone'],       views:445, favorites:52, createdAt:'2025-04-25', available:true, images: IMAGES.iphone15,      description:'Natural Titanium, full box. Battery 94%. Zero damage.' },
  { id:'p5',  title:'Trek Marlin 7 Mountain Bike',        price:200,  currency:'USD', category:'sports',      condition:'good',      location:'Betania, Panama City',        lat:8.9712, lng:-79.5334, seller:'u4', tags:['bike','mtb'],           views:78,  favorites:7,  createdAt:'2025-04-19', available:true, images: IMAGES.trekBike,      description:'Trek Marlin 7 size M, hydraulic brakes, front suspension. Perfect mechanical condition.' },
  { id:'p6',  title:'Design Books Collection ×12',        price:30,   currency:'USD', category:'books',       condition:'excellent', location:'San Francisco, Panama City',  lat:8.9977, lng:-79.5196, seller:'u3', tags:['design','books'],       views:43,  favorites:12, createdAt:'2025-04-21', available:true, images: IMAGES.designBooks,   description:'Pentagram, Taschen and more. All in excellent condition.' },
  { id:'p7',  title:'LG UltraWide 34" Monitor',           price:100,  currency:'USD', category:'electronics', condition:'good',      location:'Obarrio, Panama City',        lat:8.9861, lng:-79.5248, seller:'u2', tags:['monitor','lg'],         views:167, favorites:24, createdAt:'2025-04-23', available:true, images: IMAGES.lgMonitor,     description:'LG 34WN80C-B WQHD curved, USB-C 60W. No dead pixels.' },
  { id:'p8',  title:'Fender Player Stratocaster',         price:580,  currency:'USD', category:'music',       condition:'excellent', location:'Río Abajo, Panama City',      lat:9.0013, lng:-79.5022, seller:'u1', tags:['fender','guitar'],      views:201, favorites:33, createdAt:'2025-04-24', available:true, images: IMAGES.fenderStrat,   description:'Polar White, Alnico V pickups. Semi-rigid case included.' },
  { id:'p9',  title:'PlayStation 5 Disc Edition',         price:480,  currency:'USD', category:'gaming',      condition:'excellent', location:'Albrook, Panama City',        lat:8.9934, lng:-79.5560, seller:'u3', tags:['ps5','gaming'],         views:312, favorites:44, createdAt:'2025-04-26', available:true, images: IMAGES.ps5,           description:'2 controllers, all cables, 3 games. Barely used.' },
  { id:'p10', title:'Vintage Leather Jacket M',            price:175,  currency:'USD', category:'fashion',     condition:'good',      location:'Casco Viejo, Panama City',   lat:8.9514, lng:-79.5354, seller:'u4', tags:['leather','jacket'],     views:89,  favorites:15, createdAt:'2025-04-27', available:true, images: IMAGES.leatherJacket, description:'Genuine leather, 90s style, brown color. Incredibly soft.' },
  { id:'p11', title:'DJI Mini 3 Pro Drone',                price:720,  currency:'USD', category:'electronics', condition:'new',       location:'Clayton, Panama City',        lat:8.9880, lng:-79.5640, seller:'u2', tags:['dji','drone'],          views:276, favorites:38, createdAt:'2025-04-28', available:true, images: IMAGES.djiMini3,      description:'RC controller, 2 batteries, carrying case. Only 3 flights.' },
  { id:'p12', title:'Rolex Submariner 116610LN',           price:11500,currency:'USD', category:'fashion',     condition:'excellent', location:'Punta Pacífica, Panama City', lat:8.9900, lng:-79.5070, seller:'u1', tags:['rolex','watch'],        views:534, favorites:71, createdAt:'2025-04-29', available:true, images: IMAGES.rolex,         description:'Full set, box and papers 2021. No service needed.' },

  // ── LOW COST ─────────────────────────────────────────────
  { id:'p13', title:'JLab Wireless Earbuds',              price:18,   currency:'USD', category:'electronics', condition:'new',       location:'Chorrera, Panama Oeste',      lat:8.8767, lng:-79.7832, seller:'u5', tags:['earbuds','audio'],      views:55,  favorites:6,  createdAt:'2025-04-28', available:true, images: IMAGES.jlabEarbuds,   description:'JLab Go Air Pop. 32h battery. Minor box damage — unit is perfect.' },
  { id:'p14', title:'IKEA Desk Lamp RANARP',              price:9,    currency:'USD', category:'home',        condition:'good',      location:'Arraiján, Panama Oeste',      lat:8.9332, lng:-79.6832, seller:'u5', tags:['lamp','ikea'],          views:22,  favorites:2,  createdAt:'2025-04-25', available:true, images: IMAGES.ikeaLamp,      description:'White RANARP lamp. Works perfectly. Moving sale.' },
  { id:'p15', title:'Oster 5-Speed Blender',              price:18,   currency:'USD', category:'home',        condition:'excellent', location:'San Miguelito, Panama City',  lat:9.0333, lng:-79.4833, seller:'u6', tags:['blender','kitchen'],    views:40,  favorites:4,  createdAt:'2025-04-22', available:true, images: IMAGES.blender,       description:'Used maybe 10 times. All functions work. Includes all cups.' },
  { id:'p16', title:'Spiderman Kids Backpack',             price:8,    currency:'USD', category:'babies',      condition:'excellent', location:'Tocumen, Panama City',        lat:9.0618, lng:-79.3839, seller:'u4', tags:['kids','backpack'],      views:18,  favorites:3,  createdAt:'2025-04-27', available:true, images: IMAGES.kidsBackpack,  description:'Almost new. My kid outgrew it fast. Perfect condition.' },
  { id:'p17', title:'X Rocker Gaming Chair',               price:55,   currency:'USD', category:'gaming',      condition:'fair',      location:'Vista Alegre, Panama City',  lat:9.0120, lng:-79.5010, seller:'u6', tags:['gaming','chair'],       views:67,  favorites:8,  createdAt:'2025-04-26', available:true, images: IMAGES.gamingChair,   description:'Built-in speakers. Some minor wear on armrests.' },
  { id:'p18', title:'Yoga Mat + Blocks Set',               price:15,   currency:'USD', category:'sports',      condition:'excellent', location:'El Valle, Coclé',             lat:8.6000, lng:-80.1333, seller:'u3', tags:['yoga','fitness'],       views:33,  favorites:5,  createdAt:'2025-04-24', available:true, images: IMAGES.yogaMat,       description:'Non-slip mat 6mm + 2 cork blocks. Barely used.' },
  { id:'p19', title:'Samsung Galaxy A14 64GB',             price:65,   currency:'USD', category:'electronics', condition:'fair',      location:'Colón City, Colón',           lat:9.3588, lng:-79.9008, seller:'u2', tags:['samsung','android'],    views:88,  favorites:11, createdAt:'2025-04-23', available:true, images: IMAGES.samsungA14,    description:'Good daily driver. Cracked back, screen perfect.' },
  { id:'p20', title:'Solid Wood Coffee Table',             price:40,   currency:'USD', category:'home',        condition:'good',      location:'David, Chiriquí',             lat:8.4278, lng:-82.4376, seller:'u3', tags:['table','furniture'],    views:29,  favorites:4,  createdAt:'2025-04-20', available:true, images: IMAGES.coffeeTable,   description:'Solid wood, 100×50cm. Pick up only.' },
  { id:'p21', title:'Nike Air Zoom Pegasus 40 US10',       price:40,   currency:'USD', category:'sports',      condition:'excellent', location:'El Dorado, Panama City',      lat:9.0049, lng:-79.5283, seller:'u1', tags:['nike','shoes'],         views:142, favorites:19, createdAt:'2025-04-27', available:true, images: IMAGES.nikePegasus,   description:'Worn 3 times only. Like new condition.' },
  { id:'p22', title:'Nintendo Switch Lite Yellow',         price:165,  currency:'USD', category:'gaming',      condition:'excellent', location:'Marbella, Panama City',       lat:8.9950, lng:-79.5180, seller:'u5', tags:['nintendo','switch'],    views:211, favorites:29, createdAt:'2025-04-26', available:true, images: IMAGES.switchLite,    description:'Includes charger and 2 games.' },
  { id:'p23', title:'Electric Kettle 1.7L',                price:10,   currency:'USD', category:'home',        condition:'good',      location:'Chitré, Herrera',             lat:7.9638, lng:-80.4275, seller:'u6', tags:['kitchen','kettle'],     views:14,  favorites:1,  createdAt:'2025-04-21', available:true, images: IMAGES.kettle,        description:'Fast boil, auto shut-off. 6 months use.' },
  { id:'p24', title:"Levi's 501 Jeans W32 L32",           price:28,   currency:'USD', category:'fashion',     condition:'excellent', location:'Casco Viejo, Panama City',   lat:8.9520, lng:-79.5340, seller:'u4', tags:['levis','jeans'],        views:76,  favorites:9,  createdAt:'2025-04-25', available:true, images: IMAGES.levisJeans,    description:'Classic straight fit, dark wash. Worn ~5 times.' },
  { id:'p25', title:'Black & Decker 18V Drill Set',        price:35,   currency:'USD', category:'tools',       condition:'good',      location:'Arraiján, Panama Oeste',      lat:8.9340, lng:-79.6840, seller:'u5', tags:['drill','tools'],        views:48,  favorites:6,  createdAt:'2025-04-22', available:true, images: IMAGES.drill,         description:'18V cordless + 20 bits. Battery holds full charge.' },
  { id:'p26', title:'JBL Clip 4 Bluetooth Speaker',        price:22,   currency:'USD', category:'electronics', condition:'good',      location:'Coronado, Panama Oeste',      lat:8.5467, lng:-79.9003, seller:'u6', tags:['jbl','speaker'],        views:93,  favorites:13, createdAt:'2025-04-24', available:true, images: IMAGES.jblClip,       description:'Waterproof, 10h battery. Minor scratch on clip only.' },
  { id:'p27', title:'Graco Lightweight Stroller',          price:45,   currency:'USD', category:'babies',      condition:'excellent', location:'San Miguelito, Panama City',  lat:9.0340, lng:-79.4840, seller:'u4', tags:['baby','stroller'],      views:37,  favorites:5,  createdAt:'2025-04-23', available:true, images: IMAGES.stroller,      description:'Easy fold umbrella stroller. Used 4 months.' },
  { id:'p28', title:'Complete Skateboard Setup 8"',        price:30,   currency:'USD', category:'sports',      condition:'good',      location:'Casco Viejo, Panama City',   lat:8.9510, lng:-79.5360, seller:'u2', tags:['skateboard','skate'],   views:61,  favorites:8,  createdAt:'2025-04-26', available:true, images: IMAGES.skateboard,    description:'Good bearings, new wheels. Great for beginners.' },
  { id:'p29', title:'Kindle Paperwhite Gen 11',            price:70,   currency:'USD', category:'electronics', condition:'excellent', location:'Santa Clara, Coclé',          lat:8.4500, lng:-80.0333, seller:'u3', tags:['kindle','ebook'],       views:54,  favorites:7,  createdAt:'2025-04-25', available:true, images: IMAGES.kindle,        description:'8GB, waterproof. Includes case.' },
  { id:'p30', title:'Ceramic Plant Pots Set ×4',           price:7,   currency:'USD', category:'home',        condition:'excellent', location:'El Cangrejo, Panama City',   lat:8.9830, lng:-79.5220, seller:'u5', tags:['plants','decor'],       views:19,  favorites:3,  createdAt:'2025-04-27', available:true, images: IMAGES.plantPots,     description:'Various sizes, matte finish. Moving sale.' },
  { id:'p31', title:'Yamaha F310 Acoustic Guitar',         price:65,   currency:'USD', category:'music',       condition:'good',      location:'David, Chiriquí',             lat:8.4290, lng:-82.4360, seller:'u6', tags:['guitar','acoustic'],    views:82,  favorites:11, createdAt:'2025-04-24', available:true, images: IMAGES.yamahaGuitar,  description:'Beginner/intermediate steel-string. No cracks.' },
  { id:'p32', title:'Wacom Intuos S Drawing Tablet',       price:17,   currency:'USD', category:'electronics', condition:'good',      location:'Vista Hermosa, Panama City',  lat:9.0090, lng:-79.5130, seller:'u3', tags:['wacom','drawing'],      views:44,  favorites:7,  createdAt:'2025-04-23', available:true, images: IMAGES.wacom,         description:'Pen included. Works perfectly with any PC/Mac.' },

  // ── EXTRA ─────────────────────────────────────────────────
  { id:'p33', title:'Wooden Picture Frames ×3',            price:7,    currency:'USD', category:'home',        condition:'excellent', location:'Bella Vista, Panama City',   lat:8.9927, lng:-79.5274, seller:'u7', tags:['frames','decor'],       views:12,  favorites:2,  createdAt:'2025-05-01', available:true, images: IMAGES.pictureFrames,  description:'Three wood picture frames 4x6". Wall hooks included.' },
  { id:'p34', title:'Adidas Ultraboost 22 US9',            price:55,   currency:'USD', category:'fashion',     condition:'good',      location:'Albrook, Panama City',        lat:8.9930, lng:-79.5570, seller:'u7', tags:['adidas','shoes'],       views:98,  favorites:14, createdAt:'2025-05-01', available:true, images: IMAGES.adidasShoes,    description:'Adidas Ultraboost 22, triple white. Worn less than 10 times.' },
  { id:'p35', title:'IKEA Floor Lamp — Free!',             price:0,    currency:'USD', category:'free',        condition:'good',      location:'Arraiján, Panama Oeste',      lat:8.9340, lng:-79.6840, seller:'u5', tags:['lamp','free','ikea'],   views:34,  favorites:8,  createdAt:'2025-05-01', available:true, images: IMAGES.ikeaFloorLamp,  description:'Giving away IKEA floor lamp. Works fine, just upgrading. Pick up only in Arraiján.' },
  { id:'p36', title:'Box of Children Books — Free',        price:0,    currency:'USD', category:'free',        condition:'good',      location:'San Miguelito, Panama City',  lat:9.0330, lng:-79.4840, seller:'u4', tags:['books','free','kids'],  views:28,  favorites:6,  createdAt:'2025-05-01', available:true, images: IMAGES.childrenBooks,  description:'Box of 15 kids books. Ages 4–8. All in good condition. Free to a good home.' },
  { id:'p37', title:'Old Laptop Parts — Free (For Repair)',price:0,    currency:'USD', category:'free',        condition:'for-parts', location:'El Dorado, Panama City',      lat:9.0049, lng:-79.5283, seller:'u8', tags:['laptop','parts','free'],views:19,  favorites:3,  createdAt:'2025-05-01', available:true, images: IMAGES.laptopParts,    description:'Old HP laptop, screen broken, for parts. RAM and SSD may still be good.' },
  { id:'p38', title:'Plastic Storage Bins ×5 — Free',     price:0,    currency:'USD', category:'free',        condition:'fair',      location:'Tocumen, Panama City',        lat:9.0620, lng:-79.3840, seller:'u6', tags:['storage','free','bins'],views:15,  favorites:2,  createdAt:'2025-05-01', available:true, images: IMAGES.storageBins,    description:'5 large plastic storage bins, various sizes. Some lid damage. Pick up only.' },
  { id:'p39', title:"Men's Shirt Collection ×5",          price:20,   currency:'USD', category:'fashion',     condition:'good',      location:'Bella Vista, Panama City',   lat:8.9927, lng:-79.5274, seller:'u7', tags:['shirts','fashion','men'],views:44,  favorites:5,  createdAt:'2025-05-01', available:true, images: IMAGES.shirts,         description:"5 men's shirts, mixed brands, size M. Sold as a bundle only." },
  { id:'p40', title:'Mini Air Purifier',                   price:25,   currency:'USD', category:'home',        condition:'good',      location:'Costa del Este, Panama City', lat:9.0076, lng:-79.4750, seller:'u2', tags:['purifier','air','home'],views:31,  favorites:4,  createdAt:'2025-05-01', available:true, images: IMAGES.airPurifier,    description:'Levoit mini air purifier. Filter replaced last month. Quiet operation.' },
  { id:'p41', title:'Resistance Bands Set ×5',             price:10,   currency:'USD', category:'sports',      condition:'new',       location:'Marbella, Panama City',       lat:8.9940, lng:-79.5200, seller:'u1', tags:['bands','fitness'],      views:56,  favorites:7,  createdAt:'2025-05-01', available:true, images: IMAGES.resBands,       description:'5 resistance levels, never opened. Sealed box.' },
  { id:'p42', title:'Portable USB-C Hub 7-in-1',           price:20,   currency:'USD', category:'electronics', condition:'excellent', location:'El Cangrejo, Panama City',   lat:8.9824, lng:-79.5230, seller:'u3', tags:['usbc','hub','adapter'], views:72,  favorites:9,  createdAt:'2025-05-01', available:true, images: IMAGES.usbHub,         description:'USB-C hub with HDMI, USB 3.0, SD card, PD charging. Perfect condition.' },
  { id:'p43', title:'Succulent Plants ×6',                 price:8,    currency:'USD', category:'home',        condition:'new',       location:'Penonomé, Coclé',             lat:8.5230, lng:-80.3580, seller:'u8', tags:['plants','succulents'],  views:23,  favorites:4,  createdAt:'2025-05-01', available:true, images: IMAGES.succulents,     description:'6 healthy succulent plants in small pots. Great for desk or windowsill.' },
  { id:'p44', title:'Protein Shaker Bottle ×2',            price:6,    currency:'USD', category:'sports',      condition:'good',      location:'Albrook, Panama City',        lat:8.9930, lng:-79.5580, seller:'u5', tags:['gym','shaker','fitness'],views:18,  favorites:2,  createdAt:'2025-05-01', available:true, images: IMAGES.shaker,         description:'2 protein shakers, 700ml each. Washed and ready.' },
  { id:'p45', title:'Toddler Toys Bundle',                 price:15,   currency:'USD', category:'babies',      condition:'good',      location:'San Miguelito, Panama City',  lat:9.0330, lng:-79.4840, seller:'u5', tags:['toys','toddler','kids'],views:26,  favorites:5,  createdAt:'2025-05-01', available:true, images: IMAGES.toddlerToys,    description:'Bundle of toddler toys: stacking rings, shape sorter, soft books. Ages 1–3.' },
  { id:'p46', title:'USB Mechanical Keyboard 60%',         price:30,   currency:'USD', category:'electronics', condition:'good',      location:'Obarrio, Panama City',        lat:8.9861, lng:-79.5250, seller:'u8', tags:['keyboard','mechanical'],views:89,  favorites:12, createdAt:'2025-05-01', available:true, images: IMAGES.mechKeyboard,   description:'60% mechanical keyboard, red switches. Minor key cap wear.' },
  { id:'p47', title:'Cooking Pots Set ×3',                 price:18,   currency:'USD', category:'home',        condition:'good',      location:'Chitré, Herrera',             lat:7.9638, lng:-80.4280, seller:'u6', tags:['pots','kitchen','cooking'],views:14, favorites:1,  createdAt:'2025-05-01', available:true, images: IMAGES.cookingPots,    description:'3 different sizes, non-stick. Lightly used, no peeling.' },
  { id:'p48', title:'Printed Art Poster 50×70',            price:5,    currency:'USD', category:'art',         condition:'new',       location:'Casco Viejo, Panama City',   lat:8.9514, lng:-79.5354, seller:'u7', tags:['poster','art','print'],  views:17,  favorites:3,  createdAt:'2025-05-01', available:true, images: IMAGES.artPoster,      description:'High quality printed art poster. Never framed. Abstract minimal style.' },
  { id:'p49', title:'HDMI Cable 2m ×2',                    price:5,    currency:'USD', category:'electronics', condition:'excellent', location:'El Dorado, Panama City',      lat:9.0049, lng:-79.5283, seller:'u2', tags:['hdmi','cable'],          views:21,  favorites:1,  createdAt:'2025-05-01', available:true, images: IMAGES.hdmiCable,      description:'2 HDMI 2.0 cables, 2m each. Work perfectly.' },
  { id:'p50', title:'Don quijote de la Mancha ×4',           price:12,   currency:'USD', category:'books',       condition:'good',      location:'David, Chiriquí',             lat:8.4280, lng:-82.4370, seller:'u3', tags:['spanish','books','learning'],views:11,favorites:2,  createdAt:'2025-05-01', available:true, images: IMAGES.spanishBooks,   description:'4 Spanish workbooks, level A2 to B2. Some highlights inside.' },
  { id:'p51', title:'Kids Drawing Tablet',                  price:12,   currency:'USD', category:'babies',      condition:'excellent', location:'Arraiján, Panama Oeste',      lat:8.9340, lng:-79.6840, seller:'u5', tags:['drawing','kids','tablet'],views:19, favorites:4,  createdAt:'2025-05-01', available:true, images: IMAGES.kidsDrawing,    description:'Color LCD drawing tablet for kids. Includes stylus and eraser.' },
  { id:'p52', title:'Massage Gun Basic',                    price:25,   currency:'USD', category:'sports',      condition:'good',      location:'Bella Vista, Panama City',   lat:8.9927, lng:-79.5274, seller:'u7', tags:['massage','recovery'],    views:44,  favorites:6,  createdAt:'2025-05-01', available:true, images: IMAGES.massageGun,     description:'Massage gun 3 speed settings, 4 heads. Battery holds 1.5h.' },
  { id:'p53', title:'Reusable Shopping Bags ×10 — Free',   price:0,    currency:'USD', category:'free',        condition:'good',      location:'Obarrio, Panama City',        lat:8.9860, lng:-79.5250, seller:'u7', tags:['bags','free','eco'],     views:8,   favorites:1,  createdAt:'2025-05-01', available:true, images: IMAGES.reusableBags,   description:'10 reusable grocery bags. Clean and ready. Just need them gone.' },
  { id:'p54', title:'Office Desk Organizer',                price:8,    currency:'USD', category:'home',        condition:'good',      location:'San Francisco, Panama City',  lat:8.9977, lng:-79.5196, seller:'u8', tags:['desk','organizer'],      views:15,  favorites:2,  createdAt:'2025-05-01', available:true, images: IMAGES.deskOrganizer,  description:'Bamboo desk organizer. Fits pens, clips, sticky notes.' },
  { id:'p55', title:'Swim Goggles + Cap Set',               price:7,    currency:'USD', category:'sports',      condition:'excellent', location:'Coronado, Panama Oeste',      lat:8.5467, lng:-79.9003, seller:'u6', tags:['swimming','goggles'],    views:22,  favorites:3,  createdAt:'2025-05-01', available:true, images: IMAGES.swimGoggles,    description:'Anti-fog goggles + silicone cap. Used twice.' },
  { id:'p56', title:'Perfume Sampler Kit ×6',               price:20,   currency:'USD', category:'fashion',     condition:'new',       location:'Marbella, Panama City',       lat:8.9940, lng:-79.5200, seller:'u1', tags:['perfume','fragrance'],   views:38,  favorites:6,  createdAt:'2025-05-01', available:true, images: IMAGES.perfume,        description:'6 travel-size perfumes. Mixed brands. Never opened.' },
  { id:'p57', title:'Wireless Mouse Logitech M705',         price:22,   currency:'USD', category:'electronics', condition:'good',      location:'El Cangrejo, Panama City',   lat:8.9824, lng:-79.5230, seller:'u2', tags:['mouse','logitech'],      views:61,  favorites:8,  createdAt:'2025-05-01', available:true, images: IMAGES.logitechMouse,  description:'Logitech M705 marathon wireless mouse. Battery lasts months. Great condition.' },
  { id:'p58', title:'Metal Water Bottle 1L',                price:10,   currency:'USD', category:'sports',      condition:'excellent', location:'Albrook, Panama City',        lat:8.9930, lng:-79.5580, seller:'u3', tags:['bottle','hydration'],    views:27,  favorites:4,  createdAt:'2025-05-01', available:true, images: IMAGES.waterBottle,    description:'Insulated 1L stainless steel bottle. Keeps cold 24h.' },
  { id:'p59', title:'Baby Monitor — Free',                  price:0,    currency:'USD', category:'free',        condition:'good',      location:'San Miguelito, Panama City',  lat:9.0330, lng:-79.4840, seller:'u5', tags:['baby','monitor','free'], views:11,  favorites:3,  createdAt:'2025-05-01', available:true, images: IMAGES.babyMonitor,    description:'Basic baby monitor, audio only. Works fine. Giving away — my kids are grown.' },
  { id:'p60', title:'Handmade Macramé Wall Decor',           price:15,   currency:'USD', category:'art',         condition:'new',       location:'Casco Viejo, Panama City',   lat:8.9514, lng:-79.5354, seller:'u7', tags:['macrame','art','decor'], views:33,  favorites:5,  createdAt:'2025-05-01', available:true, images: IMAGES.macrame,        description:'Handmade macramé wall hanging. 40cm wide. Natural cotton rope.' },
  { id:'p61', title:'Broken iPhone 12 — For Parts',         price:20,   currency:'USD', category:'electronics', condition:'for-parts', location:'Tocumen, Panama City',        lat:9.0620, lng:-79.3840, seller:'u8', tags:['iphone','parts'],        views:45,  favorites:5,  createdAt:'2025-05-01', available:true, images: IMAGES.brokenIphone,   description:'iPhone 12 with shattered screen. Back glass intact. Logic board unknown.' },
  { id:'p62', title:'Jump Rope — Speed',                    price:6,    currency:'USD', category:'sports',      condition:'excellent', location:'Vista Alegre, Panama City',  lat:9.0120, lng:-79.5010, seller:'u4', tags:['jumprope','fitness'],    views:14,  favorites:1,  createdAt:'2025-05-01', available:true, images: IMAGES.jumpRope,       description:'Speed jump rope with ball bearings. Adjustable length.' },
  { id:'p63', title: 'villand saga manga',                  price:4,    currency: 'USD',  category: 'books',  condition:  'excellent', location: 'San miguel, Panama City', lat: 9.0330, lng: -79.4840, seller: 'u8', tags:['manga', 'books'],     views:36,   favorites:6,  createdAt: '2025-05-01', available:true, images: IMAGES.villandsaga, description:  'villand saga manga, first edition, in excenllent condition, never read, perfect for collectors.' }
];